# Generated by Django 2.1.2 on 2019-01-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_num_2',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
