# Generated by Django 2.1.2 on 2019-01-11 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('feature_1', models.CharField(blank=True, max_length=400)),
                ('feature_2', models.CharField(blank=True, max_length=400)),
                ('feature_3', models.CharField(blank=True, max_length=400)),
                ('MRP', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('delivery_charge', models.IntegerField()),
                ('Warranty_info', models.CharField(max_length=200)),
                ('photo_main_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_main_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Category')),
            ],
        ),
    ]
