# Generated by Django 2.1.2 on 2019-01-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190112_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo_main_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
