# Generated by Django 2.1.2 on 2019-01-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_photo_main_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
    ]
