# Generated by Django 2.1.2 on 2019-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_has_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='PC-12', max_length=20),
            preserve_default=False,
        ),
    ]
