# Generated by Django 2.1.2 on 2019-01-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190112_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_1',
        ),
    ]
