# Generated by Django 2.1.2 on 2019-01-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190112_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo_one',
            new_name='photo_1',
        ),
    ]
